export enum Movies{
   POPULAR_MOVIES_START = '[POPULAR START] Popular Start',
   POPULAR_MOVIES_SUCCESS = '[POPULAR SUCCESS] Popular Success',
   TOP_MOVIES_START = '[TOP START] TOP Start',
   TOP_MOVIES_SUCCESS = '[TOP SUCCESS] TOP Success',
}